stages:
    - deploy
    - cleanup

deploy_review_app:
  stage: deploy
  script:   
    - echo "Deploying Review App..."
    - echo "Your deploy commands here..."
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://${CI_PROJECT_NAMESPACE}.pages.unistra.fr/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/public/index.html
  only:
    - merge_requests

cleanup_review_app:
  stage: cleanup
  script:
    - echo "Stopping Review App..."
    - echo "Your cleanup commands here..."
  environment:
    name: review/$CI_COMMIT_REF_NAME
  only:
    - merge_requests
  when: manual
